#!/bin/sh
#
# @name DRAKKAR Y_VTOL_Tiltrotor
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer ruexue
#
# @output MAIN1 Motor right
# @output MAIN2 Motor left
# @output MAIN3 Motor back
# @output MAIN4 empty
# @output AUX1 tilt rear
# @output AUX2 Aileron left
# @output AUX3 Aileron right
# @output AUX4 Elevator
# @output AUX5 Rudder
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default MC_PITCHRATE_D  0.003
param set-default MC_PITCHRATE_P  0.15
param set-default MC_PITCH_P  6
param set-default MC_ROLLRATE_D   0.003
param set-default MC_ROLLRATE_P   0.15
param set-default MC_ROLL_P   6
param set-default MC_YAWRATE_MAX  120
param set-default MC_YAWRATE_P    0.27
param set-default MC_YAW_P    2.5

param set-default MC_YAWRATE_P 0.3
param set-default MPC_LAND_SPEED 1.2
param set-default MPC_TKO_SPEED 2.5
param set-default MPC_Z_VEL_MAX_UP 3

param set-default PWM_MAIN_RATE 400

param set-default VT_B_TRANS_DUR  1
param set-default VT_F_TRANS_DUR  1.2
param set-default VT_F_TR_OL_TM   4
param set-default VT_FW_DIFTHR_EN 1
param set-default VT_FW_DIFTHR_SC 0.17
param set-default VT_FW_MOT_OFFID 3
param set-default VT_FW_PERM_STAB 0
param set-default VT_IDLE_PWM_MC 1100
param set-default VT_MOT_ID 123
param set-default VT_TILT_FW  1
param set-default VT_TILT_MC  0
param set-default VT_TILT_TRANS   0.45
param set-default VT_TRANS_MIN_TM 1.2
param set-default VT_TRANS_P2_DUR 1.3
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_TYPE 1
set MAV_TYPE 21

set MIXER Ruexue3
set MIXER_AUX y_vtol_ruexue

set PWM_OUT 1234
